ALTER TABLE public.chat_rules 
ADD COLUMN IF NOT EXISTS min_lead_score INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS intent_levels TEXT[] DEFAULT NULL;

ALTER TABLE public.comment_rules 
ADD COLUMN IF NOT EXISTS min_lead_score INTEGER DEFAULT NULL,
ADD COLUMN IF NOT EXISTS intent_levels TEXT[] DEFAULT NULL;
