export default function PrivacyPage() {
  return (
    <div className="card" style={{ maxWidth: '800px', margin: '40px auto', padding: '40px' }}>
      <h1 style={{ marginBottom: '24px' }}>Privacy Policy</h1>
      
      <div style={{ lineHeight: '1.6', color: 'var(--text-secondary)' }}>
        <p>Last updated: {new Date().toLocaleDateString()}</p>
        
        <h3 style={{ color: 'var(--text-primary)', marginTop: '24px' }}>1. Data Collection</h3>
        <p>When you use AutometaBot, we collect the following types of information:</p>
        <ul>
          <li><strong>Account Information:</strong> Name, email address, and authentication data.</li>
          <li><strong>Integration Data:</strong> Facebook and Instagram Page tokens, necessary to provide automated messaging services.</li>
          <li><strong>Conversational Data:</strong> Chat logs generated by your customers are temporarily processed by our AI models to generate accurate responses.</li>
        </ul>

        <h3 style={{ color: 'var(--text-primary)', marginTop: '24px' }}>2. How We Use Your Data</h3>
        <p>Your data is used strictly to provide, maintain, and improve the AutometaBot service. We do not sell your conversational data or customer information to third parties.</p>

        <h3 style={{ color: 'var(--text-primary)', marginTop: '24px' }}>3. AI Processing & Third Parties</h3>
        <p>To generate AI responses, chat inputs and relevant sections of your uploaded knowledge base are sent to secure, industry-leading AI providers (such as OpenAI, Anthropic, or OpenRouter). These providers are contractually obligated not to use API data to train their public models.</p>

        <h3 style={{ color: 'var(--text-primary)', marginTop: '24px' }}>4. Data Security</h3>
        <p>We implement robust security measures, including database encryption, secure authentication (via Supabase), and Row Level Security (RLS) to ensure your data is accessible only to you.</p>

        <h3 style={{ color: 'var(--text-primary)', marginTop: '24px' }}>5. Your Rights</h3>
        <p>You have the right to request the deletion of your account and all associated data at any time. To do so, please contact our support team.</p>
      </div>
    </div>
  );
}
